In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.utils import shuffle
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
#making corpus or words from comments
import re
from nltk.stem.porter import PorterStemmer
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
dataset = pd.read_csv(r'C:\Users\hamza jamil\Downloads\New folder (5)\Roman Urdu DataSet.csv',encoding='cp437')
dataset

Comment sentiment  nan
0      Sai kha ya her kisi kay bus ki bat nhi hai lak...  Positive  NaN
1                                              sahi bt h  Positive  NaN
2                                            Kya bt hai,  Positive  NaN
3                                             Wah je wah  Positive  NaN
4                                   Are wha kaya bat hai  Positive  NaN
...                                                  ...       ...  ...
14641  Han mene abhi dekhna start kia last 3 episodes se   Neutral  NaN
14642  Kitna acha bhai hai kehta me daant kha lun ga ...  Positive  NaN
14643            DJ ko aik pappi idrrr aikk pappii udrr   Positive  NaN
14644             Dj ki wja se drama dykna ka dil krta h  Positive  NaN
14645         Very Bad DJ Ne Ja Video Wap ni ki Arsal ko  Negative  NaN

[14646 rows x 3 columns]

In [3]:

# label selection
y=dataset.iloc[:,1].values
labelEnocder_y=LabelEncoder()
y=labelEnocder_y.fit_transform(y)
# 2 postive 0 negative 1 nuetraldataset.sentiment.unique()

In [4]:
corpus=[]
stopwords=['ai', 'ayi', 'hy', 'hai', 'main', 'ki', 'tha', 'koi', 'ko', 'sy', 'woh', 'bhi', 'aur', 'wo', 'yeh', 'rha', 'hota', 'ho', 'ga', 'ka', 'le', 'lye', 'kr', 'kar', 'lye', 'liye', 'hotay', 'waisay', 'gya', 'gaya', 'kch', 'ab', 'thy', 'thay', 'houn', 'hain', 'han', 'to', 'is', 'hi', 'jo', 'kya', 'thi', 'se', 'pe', 'phr', 'wala', 'waisay', 'us', 'na', 'ny', 'hun', 'rha', 'raha', 'ja', 'rahay', 'abi', 'uski', 'ne', 'haan', 'acha', 'nai', 'sent', 'photo', 'you', 'kafi', 'gai', 'rhy', 'kuch', 'jata', 'aye', 'ya', 'dono', 'hoa', 'aese', 'de', 'wohi', 'jati', 'jb', 'krta', 'lg', 'rahi', 'hui', 'karna', 'krna', 'gi', 'hova', 'yehi', 'jana', 'jye', 'chal', 'mil', 'tu', 'hum', 'par', 'hay', 'kis', 'sb', 'gy', 'dain', 'krny', 'tou']
for i in range(0,14646):
    review = re.sub('[^a-zA-Z]',' ',dataset.iloc[:,0].values[i])
    review=review.lower()
    review=review.split()
    review=[word for word in review if not word in stopwords]
    review=' '.join(review)
    corpus.append(review)

In [5]:
cv=CountVectorizer(max_features=2500)
x=cv.fit_transform(corpus).toarray()

In [6]:
import pickle
pickle.dump(cv, open('urdu_counter1.pkl', 'wb'))

In [7]:
#spliting dataset into train and test set
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [8]:
classifier=LogisticRegression(random_state=10,solver='liblinear',multi_class='auto')
classifier.fit(x_train,y_train)



LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=10, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
y_pred=classifier.predict(x_test)
y_pred

array([2, 1, 1, ..., 1, 0, 1])

In [10]:
print('Accuracy is {} '.format(accuracy_score(y_test, y_pred)))

Accuracy is 0.6436860068259386 


In [11]:
pickle.dump(classifier, open('urdu_Modell.pkl', 'wb'))

In [12]:
model=pickle.load(open(r'C:\Users\hamza jamil\urdu_Modell.pkl','rb'))
model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=10, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
counter=pickle.load(open(r'C:\Users\hamza jamil\urdu_counter1.pkl','rb'))
counter

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=2500, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [14]:
message='ya achi baat ha'
data=[message]

In [15]:
p1=cv.fit_transform(data).toarray()
p1

array([[1, 1, 1, 1]], dtype=int64)

In [17]:
classifier.predict(p1)

ValueError: X has 4 features per sample; expecting 2500

In [36]:
corpus

['sai kha her kisi kay bus bat nhi lakin hal kal bi aj aj bi sirf aus say bus',
 'sahi bt h',
 'bt',
 'wah je wah',
 'are wha kaya bat',
 'wah baat likhi',
 'wha itni sari khubiya',
 'itni khubiya',
 'allah rehm farma hm sab or zalimo hidayat ameen',
 'please everyone allah s w t naam hamesha bary lawzo likha kary he zaat sub say bari hey',
 'mere rab bra kreem mulk k halat pr reham frma watn e aziz hifazat frma amin',
 'jaago pakistani coom jaago ye humary nokar humarey tex inko tankha milti h or ye pakitani awam martey jaago pakistan key logo',
 'kia kia jae kon sacha ha allah jany pak kese bdl sakta ha i think nsl ase e guzr jain bd me hua pta ni',
 'afsos garip insan kha jay allah lati me awaz zulum kry allah lati pary',
 'allah insaaf karey',
 'allah musalman phir dor e jahalat me jaraha h hiyaday farma logo awam zindgiyo azab bana rahy inko garak kardy',
 'je thik kaha right',
 'jee ye he',
 'maa cheez e ase ha jis namil badl ni',
 'wah wah toh',
 'jee ye he',
 'zenda bad yar',
 

In [62]:
y

array([2, 2, 2, ..., 2, 2, 0])